force-app/main/default/objects/Contract_Resource__c/Contract_Resource__c.object-meta.xml
<CustomObject>
    <label>Contract Resource</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Contract Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Resource__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <displayFormat>PAYLI-{000}</displayFormat>
        <label>Payment Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/fields/Contract_Resource__c.field-meta.xml
<CustomField>
    <fullName>Contract_Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract Resource</label>
    <referenceTo>Contract_Resource__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/dao_PaymentsLineItem.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public with sharing class dao_PaymentsLineItem extends sql_Dao {

    public dao_PaymentsLineItem() {
      setSObject(Payment_Line_Item__c.sObjectType);

      addField(Payment_Line_Item__c.Id);
      addField(Payment_Line_Item__c.Name);
      addField(Payment_Line_Item__c.Amount__c);
      addField(Payment_Line_Item__c.Minutes__c);
      addField(Payment_Line_Item__c.Contract_Resource__c);
      addField(Payment_Line_Item__c.Payment__c);
      addField(Payment_Line_Item__c.Rate__c);
    }


    public List<Payment_Line_Item__c> findByPayment(String paymentId) {
       return (List<Payment_Line_Item__c>)getWhere(sql_Criteria.Equals(Payment_Line_Item__c.Payment__c, paymentId));
    }
}