force-app/main/default/objects/Contract_Resource__c/Contract_Resource__c.object-meta.xml
<CustomObject>
    <label>Contract Resource</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Contract Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Resource__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Entry__c/Expense_Entry__c.object-meta.xml
<CustomObject>
    <label>Expense Entry</label>
    <nameField>
        <displayFormat>EE-{000000000}</displayFormat>
        <label>Expense Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Entry__c/fields/Contract_Resource__c.field-meta.xml
<CustomField>
    <fullName>Contract_Resource__c</fullName>
    <label>Contract Resource</label>
    <referenceTo>Contract_Resource__c</referenceTo>
    <relationshipLabel>Expense Entries</relationshipLabel>
    <relationshipName>Expense_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Entry__c/fields/TimesheetId__c.field-meta.xml
<CustomField>
    <fullName>TimesheetId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timesheet Id</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Expense Entries</relationshipLabel>
    <relationshipName>Expense_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/Timesheet_Entry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TE-{000000000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_Entry__c/fields/Contract_Resource__c.field-meta.xml
<CustomField>
    <fullName>Contract_Resource__c</fullName>
    <label>Contract Resource</label>
    <referenceTo>Contract_Resource__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Is_Approved__c.field-meta.xml
<CustomField>
    <fullName>Is_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/TimesheetId__c.field-meta.xml
<CustomField>
    <fullName>TimesheetId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TimesheetId</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Subcontractor_Rate__c.field-meta.xml
<CustomField>
    <fullName>Subcontractor_Rate__c</fullName>
    <label>Subcontractor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/dao_User.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public with sharing class dao_User extends sql_Dao {
    public dao_User() {
        setSObject(User.sObjectType);

        addField(User.Id);
        addField(User.Name);
        addField(User.Subcontractor_Rate__c	);
    }

    public User findOne(String id) {
          List<User> users = getWhere(sql_Criteria.Equals(User.Id, id));

          if(users.isEmpty()) {
               return null;
          }

          return users[0];
    }

    public User findOneByTimesheet(String timesheetId) {
        List<Timesheet_entry__c> timesheetEntries = [SELECT Employee__c FROM Timesheet_entry__c WHERE TimesheetId__c = :timesheetId LIMIT 1];

        if(timesheetEntries.isEmpty()) {
            return null;
        }

        List<User> users = [SELECT Name FROM User WHERE Id = :timesheetEntries.get(0).Employee__c LIMIT 1];

        if(users.isEmpty()) {
            return null;
        }
        
        return users.get(0);
    }

    public List<User> findAll() {
       Set<String> standardUsers = new Set<String> {//TODO:review standart | all?
           'Automated Process',
           'Data.com Clean',
           'Integration User',
           'Security User',
           'Chatter Expert'
       };

       return (List<User>)getWhere(sql_Criteria.ValueNotIn(User.Name, standardUsers));
    }

    public List<User> findAllByIds(Set<String> ids) {
        if(ids == null || ids.isEmpty()) {
            return new List<User>();
        }

        return (List<User>)getWhere(sql_Criteria.ValueIn(User.Id, ids));
    }


    public List<User> findAllWithTimesheetEntries() {
        sql_Query timesheetEntriesQuery = new sql_Query();

        timesheetEntriesQuery.setSObject('Timesheet_Entries__r');
        
        timesheetEntriesQuery.addField('Id');
        timesheetEntriesQuery.addField('Date__c');
        timesheetEntriesQuery.addField('Minutes__c');
        timesheetEntriesQuery.addField('Employee__c');
        timesheetEntriesQuery.addField('Is_Approved__c');
        timesheetEntriesQuery.addField('LastModifiedDate');

        addChild(timesheetEntriesQuery);

        List<User> users = findAll();

        query.children.clear();

        return users;
    }

    public List<User> findAllWithExpenseEntries() {
        List<AggregateResult> expenses = [
            SELECT 
                    Contract_resource__r.Employee__c  employeeId
            FROM 
                    Expense_entry__c 
            GROUP BY 
                    Contract_resource__r.Employee__c                    
        ];

        Set<String> userIds = new Set<String>();

        for(AggregateResult expense : expenses) {
            String employeeId = (String)expense.get('employeeId');
            userIds.add(employeeId);
        }

        List<User> users = findAllByIds(userIds);

        return users;
    }
}