force-app/main/default/objects/Contract/fields/Client_Manager__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/Contract_Resource__c.object-meta.xml
<CustomObject>
    <label>Contract Resource</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Contract Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Resource__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Resources</relationshipLabel>
    <relationshipName>Contract_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/ApprovedBy__c.field-meta.xml
<CustomField>
    <fullName>ApprovedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Contract_Resource__c.field-meta.xml
<CustomField>
    <fullName>Contract_Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract Resource</label>
    <referenceTo>Contract_Resource__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Timesheet End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/LastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate__c</fullName>
    <label>Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Timesheet Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dao_Timesheet.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public with sharing class dao_Timesheet extends sql_Dao {
      public dao_Timesheet() {
            setSObject(Timesheet__c.sObjectType);

            addField(Timesheet__c.Id);
            addField(Timesheet__c.Name);
            addField(Timesheet__c.StartDate__c);
            addField(Timesheet__c.EndDate__c);
            addField(Timesheet__c.Status__c);
            addField(Timesheet__c.Approved__c);
            addField(Timesheet__c.ApprovedBy__c);
            addField(Timesheet__c.LastModifiedDate__c);
            addField(Timesheet__c.CreatedDate__c);
            addField(Timesheet__c.Contract_Resource__c);
      }

      public Timesheet__c findOne(String timesheetId) {
            List<Timesheet__c> timesheets = [
                  SELECT 
                        Id,
                        Name,
                        StartDate__c,
                        EndDate__c,
                        Status__c,
                        Approved__c,
                        ApprovedBy__c,
                        LastModifiedDate__c,
                        CreatedDate__c,
                        Contract_Resource__c,
                        Contract_Resource__r.Contract__c,
                        Contract_Resource__r.Employee__c,
                        Contract_Resource__r.Rate__c,
                        Contract_Resource__r.Contract__r.Client_Manager__c,
                        Contract_Resource__r.Contract__r.ContractNumber
                  FROM 
                        Timesheet__c
                  WHERE 
                        Id =: timesheetId      
            ];

            return timesheets[0];
      }

      public List<Timesheet__c> findAll() {
            List<Timesheet__c> timesheets = [
                  SELECT 
                        Id,
                        Name,
                        StartDate__c,
                        EndDate__c,
                        Status__c,
                        Approved__c,
                        ApprovedBy__c,
                        LastModifiedDate__c,
                        CreatedDate__c,
                        Contract_Resource__c,
                        Contract_Resource__r.Contract__c,
                        Contract_Resource__r.Employee__c
                  FROM 
                        Timesheet__c
            ];

            return timesheets;
      }

      public List<Timesheet__c> findAllByIds(Set<String> ids) {
            if(ids == null || ids.isEmpty()) {
                  return new List<Timesheet__c>();
            }

            return (List<Timesheet__c>)getWhere(sql_Criteria.ValueIn(Timesheet__c.Id, ids));
      }

      //TODO: Rename: not for invoice.
   /*   public List<Timesheet__c> findAllForInvoice(Set<String> timesheetsIds, Date startDate, Date endDate) {//TODO:review and refactor. Duplicate. findAll
            return [
                  SELECT
                        Id,
                        StartDate__c,
                        EndDate__c,
                        Status__c
                  FROM 
                        Timesheet__c
                  WHERE 
                        Id IN :timesheetsIds
                  AND
                        StartDate__c >= :startDate
                  AND
                        EndDate__c <= :endDate
                  AND 
                        Status__c = 'Approved'  
            ];
      }*/

      public List<Timesheet__c> findAllByContractResources(Set<String> contractResources) {//TODO:review and refactor. Duplicate. findAll
            return [
                  SELECT
                        Id,
                        StartDate__c,
                        EndDate__c,
                        Status__c,
                        Contract_Resource__c
                  FROM 
                        Timesheet__c
                  WHERE 
                        Contract_Resource__c IN :contractResources
            ];
      }


      public List<Timesheet__c> findAllForInvoice(Set<String> contractResources, Date startDate, Date endDate) {//TODO:review and refactor. Duplicate. findAll
            return [
                  SELECT
                        Id,
                        StartDate__c,
                        EndDate__c,
                        Status__c,
                        Contract_Resource__c,
                        Contract_Resource__r.Rate__c
                  FROM 
                        Timesheet__c
                  WHERE 
                        Contract_Resource__c IN :contractResources
                  AND
                        StartDate__c >= :startDate
                  AND
                        EndDate__c <= :endDate
                  AND 
                        Status__c = 'Approved'  
            ];
      }
}