force-app/main/default/objects/Contract/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/Contract_Resource__c.object-meta.xml
<CustomObject>
    <label>Contract Resource</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Contract Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Resource__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Resources</relationshipLabel>
    <relationshipName>Contract_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Resources</relationshipLabel>
    <relationshipName>Contract_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Subcontractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Subcontractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subcontractor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Resources</relationshipLabel>
    <relationshipName>Contract_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dao_ContractResource.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public with sharing class dao_ContractResource extends sql_Dao {
    public dao_ContractResource() {
        setSObject(Contract_Resource__c.sObjectType);

        addField(Contract_Resource__c.Id);
        addField(Contract_Resource__c.Contract__c);
        addField(Contract_Resource__c.Employee__c);
        addField(Contract_Resource__c.Subcontractor_Account__c);
        addField(Contract_Resource__c.Product__c);
        addField(Contract_Resource__c.Rate__c);
    }

    public Contract_Resource__c findOne(String contractId, String employeeId) {
        String contractCriteria =  sql_Criteria.Equals(Contract_Resource__c.Contract__c, contractId);
        String employeeCriteria =  sql_Criteria.Equals(Contract_Resource__c.Employee__c, employeeId);

        List<String> andCriteria = new List<String>{contractCriteria, employeeCriteria};

        List<Contract_Resource__c> listContractResources = (List<Contract_Resource__c>)getWhere(sql_Criteria.AndCriterias(andCriteria));

        if(listContractResources.isEmpty()) {
            return null;
        }

        return listContractResources[0];
    }

    public Contract_Resource__c findOneById(String id) {
        List<Contract_Resource__c> contractResources = getWhere(sql_Criteria.Equals(Contract_Resource__c.Id, id));
        
        if(contractResources.isEmpty()) {
            return null;
        }

        return contractResources[0];
    }

    public List<Contract_Resource__c> findAll() {
        return (List<Contract_Resource__c>)getAll();
    }

    public List<Contract_Resource__c> findAllByIds(Set<String> ids) {
        if(ids != null && ids.isEmpty()) {
            return new List<Contract_Resource__c>();
        }

        return (List<Contract_Resource__c>)getWhere(sql_Criteria.ValueIn(Contract_Resource__c.Id, ids));
    }

    public List<Contract_Resource__c> findAllByAccount(String accountId) {
        List<Contract_Resource__c> listContractResources = [
            SELECT 
                  id,
                  Employee__c,
                  Product__c,
                  Rate__c,
                  Contract__c,
                  Contract__r.ContractNumber
            FROM
                  Contract_Resource__c
            WHERE 
                  contract__r.AccountId = :accountId          
        ];

        return listContractResources;
    }
    
    public List<Contract_Resource__c> findAllByContracts(Set<String> contractsIds) {
        if(contractsIds == null || contractsIds.isEmpty()) {
            return new List<Contract_Resource__c>();
        }
        return (List<Contract_Resource__c>)getWhere(sql_Criteria.ValueIn(Contract_Resource__c.Contract__c, contractsIds));
    }

    public List<Contract_Resource__c> findAllByUser(String userId) {
        return (List<Contract_Resource__c>)getWhere(sql_Criteria.Equals(Contract_Resource__c.Employee__c, userId));
    }

    public List<Contract_Resource__c> findAllWithSubcontractor() {
        return (List<Contract_Resource__c>)getWhere(sql_Criteria.IsNotNull(Contract_Resource__c.Subcontractor_Account__c));
    }

    public List<Contract_Resource__c> findAllByParams(Set<String> contractsIds, String employeeId) {
        List<String> criterias = new List<String>();

        if(contractsIds != null && !contractsIds.isEmpty()) {
            criterias.add(sql_Criteria.ValueIn(Contract_Resource__c.Contract__c, contractsIds));
        }

        if(String.isNotBlank(employeeId)) {
            criterias.add(sql_Criteria.Equals(Contract_Resource__c.Employee__c, employeeId));
        }

        String criteria = '';

        if(!criterias.isEmpty()) {
            criteria = sql_Criteria.AndCriterias(criterias);
        }
        
        return (List<Contract_Resource__c>)getWhere(criteria);
    }
}