force-app/main/default/objects/Contract/fields/Is_Managed_Services__c.field-meta.xml
<CustomField>
    <fullName>Is_Managed_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Managed Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Case_Allotment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Case_Allotment__c</fullName>
    <label>Monthly Case Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Case_Overage__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Case_Overage__c</fullName>
    <label>Monthly Case Overage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <label>Monthly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Developer_Hour_Overage__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Developer_Hour_Overage__c</fullName>
    <label>Monthly Developer Hour Overage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Developer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Developer_Hours__c</fullName>
    <label>Monthly Developer Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/Monthly_Managed_Service__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service</label>
    <nameField>
        <displayFormat>MMS-{000000000}</displayFormat>
        <label>Monthly Managed Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Monthly Managed Services</relationshipLabel>
    <relationshipName>Monthly_Managed_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Case_Allotment__c.field-meta.xml
<CustomField>
    <fullName>Case_Allotment__c</fullName>
    <inlineHelpText>Number of cases available, including what was carried over from last month.</inlineHelpText>
    <label>Case Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Case_Overage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Case_Overage_Cost__c</fullName>
    <inlineHelpText>Charged by the Case.</inlineHelpText>
    <label>Case Overage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Cases_to_Carryover__c.field-meta.xml
<CustomField>
    <fullName>Cases_to_Carryover__c</fullName>
    <formula>IF(((Case_Allotment__c -  Total_Cases__c) &lt; 0), 0, Case_Allotment__c -  Total_Cases__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cases to Carryover</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Developer_Hours__c</fullName>
    <inlineHelpText>Number of developer hours available, including what was carried over from last month.</inlineHelpText>
    <label>Developer Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Hours_to_Carryover__c.field-meta.xml
<CustomField>
    <fullName>Developer_Hours_to_Carryover__c</fullName>
    <formula>IF(((Developer_Hours__c -  Total_Developer_Hours__c) &lt; 0), 0, Developer_Hours__c -  Total_Developer_Hours__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Developer Hours to Carryover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Overage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Developer_Overage_Cost__c</fullName>
    <inlineHelpText>Charged for each hour over.</inlineHelpText>
    <label>Developer Overage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Monthly_Base_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Base_Cost__c</fullName>
    <label>Monthly Base_Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/Monthly_Managed_Service_Activity__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service Activity</label>
    <nameField>
        <displayFormat>MMSA-{000000000}</displayFormat>
        <label>Monthly Managed Service Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Service Activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <label>Date Opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Monthly_Managed_Service__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Managed_Service__c</fullName>
    <label>Monthly Managed Service</label>
    <referenceTo>Monthly_Managed_Service__c</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Who_Closed__c.field-meta.xml
<CustomField>
    <fullName>Who_Closed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who Closed</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Who_Opened__c.field-meta.xml
<CustomField>
    <fullName>Who_Opened__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who Opened</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/service_ManagedServiceCase.cls
public with sharing class service_ManagedServiceCase extends service_Base
{
	private dao_Contract daoContract = new dao_Contract();
	private dao_MonthlyManagedService daoMonthlyManagedService = new dao_MonthlyManagedService();
	private dao_MonthlyManagedServiceActivity daoMonthlyManagedServiceActivity = new dao_MonthlyManagedServiceActivity();

	private Map<Id, List<Contract>> contractsMap;
	private Map<Id, List<Monthly_Managed_Service__c>> mmsMap;
	private Map<Id, Monthly_Managed_Service_Activity__c> mmsaMap;

	public override void process(service_Request request, service_Response response)
	{
		System.debug('### service_ManagedServiceCase.process');

		List<Case> cases = (List<Case>) request.Parameters.get('cases');

		if (cases != null && !cases.isEmpty())
		{
			Set<Id> acctIds = new Set<Id>();
			Set<Id> caseIds = new Set<Id>();

			for (Case tcase : cases)
			{
				acctIds.add(tcase.AccountId);
				caseIds.add(tcase.Id);
			}

			if (!acctIds.isEmpty())
			{
				System.debug('### service_ManagedServiceCase.process - Getting Contracts and Monthly Managed Services');

				getContractsMap(acctIds);
				getMonthlyManagedServicesMap(acctIds);
			}

			if (!caseIds.isEmpty())
			{
				System.debug('### service_ManagedServiceCase.process - Getting Monthly Managed Services Activities');

				getMonthlyManagedServiceActivitiesMap(caseIds);
			}

			if (cases != null && !cases.isEmpty())
			{
				List<Monthly_Managed_Service_Activity__c> mmsaListToInsert = new List<Monthly_Managed_Service_Activity__c>();
				
				for (Case tcase : cases)
				{
					Contract tcontract = getContract(tcase.AccountId, tcase.ClosedDate);

					if (tcontract != null && tcontract.Is_Managed_Services__c == true)
					{
						System.debug('### service_ManagedServiceCase.process - Found Contract');

						Decimal caseAllotment = tcontract.Monthly_Case_Allotment__c;
						Decimal developerHours = tcontract.Monthly_Developer_Hours__c;
						Decimal caseOverage = tcontract.Monthly_Case_Overage__c;
						Decimal developerHoursOverage = tcontract.Monthly_Developer_Hour_Overage__c;
						Decimal monthlyCost = tcontract.Monthly_Cost__c;

						Monthly_Managed_Service__c mms = getMonthlyManagedService(tcase.AccountId, tcase.ClosedDate);
						Monthly_Managed_Service__c pmms = getPreviousMonthlyManagedService(tcase.AccountId, tcase.ClosedDate);

						if (mms.Id == null)
						{
							System.debug('### service_ManagedServiceCase.process - Creating new Monthly Managed Service');

							Date bdate = tcase.ClosedDate.date().toStartOfMonth();
							Integer daysInMonth = Date.daysInMonth(bdate.year(), bdate.month());
							Date edate = bdate.addDays(daysInMonth - 1);

							if (pmms != null)
							{
								System.debug('### service_ManagedServiceCase.process - Carrying Over from Previous Month');
								caseAllotment = caseAllotment + pmms.Cases_to_Carryover__c;
								developerHours = developerHours + pmms.Developer_Hours_to_Carryover__c;
							}

							mms.Account__c = tcase.AccountId;
							mms.Begin_Date__c = bdate;
							mms.End_Date__c = edate;
							mms.Case_Allotment__c = caseAllotment;
							mms.Case_Overage_Cost__c = caseOverage;
							mms.Developer_Hours__c = developerHours;
							mms.Developer_Overage_Cost__c = developerHoursOverage;
							mms.Monthly_Base_Cost__c = monthlyCost;
							insert mms;
						}

						Monthly_Managed_Service_Activity__c mmsa = mmsaMap.get(tcase.Id);

						if (mmsa == null)
						{
							System.debug('### service_ManagedServiceCase.process - Getting Contracts and Monthly Managed Service Activity'); 
							
							mmsa = new Monthly_Managed_Service_Activity__c();
							mmsa.Activity_Type__c = 'Case';
							mmsa.Case__c = tcase.Id;
							mmsa.Date_Closed__c = tcase.ClosedDate.date();
							mmsa.Date_Opened__c = tcase.CreatedDate.date();
							mmsa.Monthly_Managed_Service__c = mms.Id;
							mmsa.Summary__c = tcase.Subject;
							mmsa.Who_Closed__c = tcase.OwnerId;
							mmsa.Who_Opened__c = tcase.ContactId;

							mmsaListToInsert.add(mmsa);
						}
					}
				}

				if (!mmsaListToInsert.isEmpty())
				{
					System.debug('### service_ManagedServiceCase.process - Inserting new Monthly Managed Services Activities');
					insert mmsaListToInsert;
				}
			}	
		}
	}

	private Monthly_Managed_Service__c getMonthlyManagedService(Id acctId, Datetime closedDate)
	{
		System.debug('### getMonthlyManagedService - AcctId: ' + acctId + ' ClosedDate: ' + closedDate);

		List<Monthly_Managed_Service__c> mmsList = mmsMap.get(acctId);

		if (mmsList != null 
		&& !mmsList.isEmpty())
		{
			for (Monthly_Managed_Service__c mms : mmsList)
			{
				if (mms.Begin_Date__c <= closedDate.date() 
				&& mms.End_Date__c >= closedDate.date())
				{
					System.debug('### getMonthlyManagedService Found Monthly Managed Service: ' + mms);
					return mms;
				}
			}
		}

		System.debug('### getMonthlyManagedService Did NOT Find Monthly Managed Service');
		
		return new Monthly_Managed_Service__c();
	}

	private Monthly_Managed_Service__c getPreviousMonthlyManagedService(Id acctId, Datetime closedDate)
	{
		System.debug('### getPreviousMonthlyManagedService - AcctId: ' + acctId + ' ClosedDate: ' + closedDate);

		List<Monthly_Managed_Service__c> mmsList = mmsMap.get(acctId);
		Date pcdate = closedDate.date().addMonths(-1);

		if (mmsList != null 
		&& !mmsList.isEmpty())
		{
			for (Monthly_Managed_Service__c mms : mmsList)
			{
				if (mms.Begin_Date__c <= pcdate 
				&& mms.End_Date__c >= pcdate)
				{
					System.debug('### getPreviousMonthlyManagedService Found Previous Monthly Managed Service: ' + mms);
					return mms;
				}
			}
		}
		
		System.debug('### getPreviousMonthlyManagedService Did NOT Find Previous Monthly Managed Service');

		return null;
	}

	private Contract getContract(Id acctId, Datetime closedDate)
	{
		System.debug('### getContract - AcctId: ' + acctId + ' ClosedDate: ' + closedDate);

		List<Contract> contracts = contractsMap.get(acctId);

		if (contracts != null 
		&& !contracts.isEmpty())
		{
			for (Contract tcontract : contracts)
			{
				if (tcontract.AccountId == acctId 
				&& tcontract.StartDate <=  closedDate.date()
				&& tcontract.EndDate >= closedDate.date())
				{
					System.debug('### getContract Found Contract: ' + tcontract);
					return tcontract;
				}
			}
		}

		System.debug('### getContract Did NOT Find Contract');

		return null;
	}

	private void getContractsMap(Set<Id> acctIds)
	{
		List<Contract> contracts = daoContract.getManagedServicesContractsByAccounts(acctIds);
		
		contractsMap = new Map<Id, List<Contract>>();

		if (contracts != null 
		&& !contracts.isEmpty())
		{
			for (Contract tcontract : contracts)
			{
				if (!contractsMap.containsKey(tcontract.AccountId))
				{
					contractsMap.put(tcontract.AccountId, new List<Contract>());
				}

				contractsMap.get(tcontract.AccountId).add(tcontract);
			}
		}
	}

	private void getMonthlyManagedServicesMap(Set<Id> acctIds)
	{
		List<Monthly_Managed_Service__c> mmsList = daoMonthlyManagedService.getMonthlyManagedServicesByAccounts(acctIds);
		
		mmsMap = new Map<Id, List<Monthly_Managed_Service__c>>();

		if (mmsList != null 
		&& !mmsList.isEmpty())
		{
			for (Monthly_Managed_Service__c mms : mmsList)
			{
				if (!mmsMap.containsKey(mms.Account__c))
				{
					mmsMap.put(mms.Account__c, new List<Monthly_Managed_Service__c>());
				}

				mmsMap.get(mms.Account__c).add(mms);
			}
		}
	}

	private void getMonthlyManagedServiceActivitiesMap(Set<Id> caseIds)
	{
		List<Monthly_Managed_Service_Activity__c> mmsaList = daoMonthlyManagedServiceActivity.getMonthlyManagedServiceActivitiesByCases(caseIds);
		
		mmsaMap = new Map<Id, Monthly_Managed_Service_Activity__c>();

		if (mmsaList != null 
		&& !mmsaList.isEmpty())
		{
			for (Monthly_Managed_Service_Activity__c mmsa : mmsaList)
			{
				if (!mmsaMap.containsKey(mmsa.Case__c))
				{
					mmsaMap.put(mmsa.Case__c, mmsa);
				}
			}
		}
	}
}