force-app/main/default/objects/CQ_Domain_Action_Binding__mdt/fields/DomainActionImplementation__c.field-meta.xml
<CustomField>
    <fullName>DomainActionImplementation__c</fullName>
    <description>What cq_IDomainAction class to .Execute</description>
    <inlineHelpText>What cq_IDomainAction class to .Execute</inlineHelpText>
    <label>DomainActionImplementation</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CQ_Domain_Action_Binding__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Order in which to fire Trigger actions on the same SObject for the same Trigger state. Multiple can exist at the same Sequence.</description>
    <inlineHelpText>Order in which to fire Trigger actions on the same SObject for the same Trigger state. Multiple can exist at the same Sequence.</inlineHelpText>
    <label>Sequence</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CQ_Domain_Action_Binding__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>The SObject to process the Trigger action for</description>
    <inlineHelpText>The SObject to process the Trigger action for</inlineHelpText>
    <label>SObject</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CQ_Domain_Action_Binding__mdt/fields/TriggeredWhen__c.field-meta.xml
<CustomField>
    <fullName>TriggeredWhen__c</fullName>
    <label>TriggeredWhen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
                <default>true</default>
                <label>Insert</label>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CQ_Domain_Action_Binding__mdt/fields/WhenToProcess__c.field-meta.xml
<CustomField>
    <fullName>WhenToProcess__c</fullName>
    <label>WhenToProcess</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>After</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cq_DomainActionBindingsSelector.cls
/**
 * Executes SOQL against CQ_Domain_Action_Binding__mdt
 */
public without sharing class cq_DomainActionBindingsSelector extends cq_SObjectSelector {
    public cq_DomainActionBindingsSelector() { super(CQ_Domain_Action_Binding__mdt.SObjectType); }

    // implement required GetDefaultFields() method
    public override Set<Schema.SObjectField> GetDefaultFields() {
        return new Set<Schema.SObjectField> {
            CQ_Domain_Action_Binding__mdt.SObject__c,
            CQ_Domain_Action_Binding__mdt.WhenToProcess__c,
            CQ_Domain_Action_Binding__mdt.TriggeredWhen__c,
            CQ_Domain_Action_Binding__mdt.DomainActionImplementation__c,
            CQ_Domain_Action_Binding__mdt.Sequence__c
        };
    }

    // implement required GetDefaultOrderBy() method
    public override List<cq_iOrderBy> GetDefaultOrderBy() {
        return new List<cq_iOrderBy> {
            cq_OrderBy.Ascending(CQ_Domain_Action_Binding__mdt.Sequence__c),
            cq_OrderBy.Ascending(CQ_Domain_Action_Binding__mdt.DomainActionImplementation__c)
        };
    }

    /**
     * Query for retrieving Trigger-specific DomainAction bindings
     * @param  targetSObject String     The SObject the Trigger is executing on
     * @param  process       process    Before/After
     * @param  action        action     Insert/Update/Delete
     * @return  List of CQ_Domain_Action_Binding__mdt entries
     */
    public List<CQ_Domain_Action_Binding__mdt> GetForTrigger(String targetSObject, String process, String action) {
        cq_iQueryFactory qf = GetQueryFactory()
            .WithCriteria(cq_Criteria.Equals(CQ_Domain_Action_Binding__mdt.SObject__c, targetSObject))
            .WithCriteria(cq_Criteria.Equals(CQ_Domain_Action_Binding__mdt.WhenToProcess__c, process))
            .WithCriteria(cq_Criteria.Equals(CQ_Domain_Action_Binding__mdt.TriggeredWhen__c, action));
        // THE PROCESS BELOW SHOULD ONLY BE REPEATED FOR CMDT SOBJECTS
        // YOU CAN NOT INSERT CMDT DURING A UNIT TEST, SO THIS HACK LETS THE UNIT TESTS HAPPEN
        // DO NOT REPEAT THIS PATTERN IN A NORMAL SOBJECT SELECTOR
        if (Test.isRunningTest()) {
            String sObjectName = Account.getSObjectType().getDescribe().getName();
            return new List<CQ_Domain_Action_Binding__mdt>{
                new CQ_Domain_Action_Binding__mdt(
                    SObject__c = sObjectName,
                    WhenToProcess__c = 'Before',
                    TriggeredWhen__c = 'Insert',
                    DomainActionImplementation__c = 'cqtest_SObjectDomain.testDomainActionOne',
                    Sequence__c = 10
                ),
                new CQ_Domain_Action_Binding__mdt(
                    SObject__c = sObjectName,
                    WhenToProcess__c = 'Before',
                    TriggeredWhen__c = 'Insert',
                    DomainActionImplementation__c = 'cqtest_SObjectDomain.testDomainActionOnenTwo',
                    Sequence__c = 10
                )
            };
        } else {
            return (List<CQ_Domain_Action_Binding__mdt>) qf.Execute();
        }
    }
}