force-app/main/default/objects/Account/fields/Send_Invoice_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Send Invoice To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Client_Manager__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <label>Commission Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_Managed_Services__c.field-meta.xml
<CustomField>
    <fullName>Is_Managed_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Managed Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Case_Allotment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Case_Allotment__c</fullName>
    <label>Monthly Case Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Case_Overage__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Case_Overage__c</fullName>
    <label>Monthly Case Overage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <label>Monthly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Developer_Hour_Overage__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Developer_Hour_Overage__c</fullName>
    <label>Monthly Developer Hour Overage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Monthly_Developer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Developer_Hours__c</fullName>
    <label>Monthly Developer Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Referral_Rate__c.field-meta.xml
<CustomField>
    <fullName>Referral_Rate__c</fullName>
    <label>Referral Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts_Salespersons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Send_Invoice_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Send Invoice To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Send Invoice To)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/Contract_Resource__c.object-meta.xml
<CustomObject>
    <label>Contract Resource</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Contract Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Resource__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Resources</relationshipLabel>
    <relationshipName>Contract_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/dao_Contract.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public with sharing class dao_Contract extends sql_Dao {
        public dao_Contract() {
                setSObject(Contract.sObjectType);

                addField(Contract.Id);
                addField(Contract.Name);        
                addField(Contract.AccountId);      
                addField(Contract.EndDate);
                addField(Contract.StartDate);
                addField(Contract.Is_Managed_Services__c);
                addField(Contract.Monthly_Case_Allotment__c);
                addField(Contract.Monthly_Case_Overage__c);
                addField(Contract.Monthly_Cost__c);
                addField(Contract.Monthly_Developer_Hour_Overage__c);
                addField(Contract.Monthly_Developer_Hours__c);
                addField(Contract.ContractNumber);
                addField(Contract.Pricebook2Id);
                addField(Contract.Salesperson__c);
                addField(Contract.Commission_Rate__c);
                addField(Contract.Referred_By__c);
                addField(Contract.Referral_Rate__c);
                addField(Contract.Client_Manager__c);
                addField(Contract.Send_Invoice_To__c);
        }

        public Contract findOne(String contractId) {
                List<Contract> contracts = [
                        SELECT 
                                Account.Name,
                                Account.Id,
                                Contract.ContractNumber,
                                Contract.Id
                        FROM 
                                Contract
                        WHERE 
                                Contract.Id = :contractId 
                        LIMIT 1                                
                ];

                if(contracts.isEmpty()) {
                        return null;
                }

                return contracts.get(0);
        }

        public Contract findOneByContractResource(String contractResourceId) {
                List<Contract> contracts = [
                        SELECT 
                                Id,
                                ContractNumber,
                                Pricebook2Id,
                                Referred_By__c,
                                Referral_Rate__c,
                                Salesperson__c,
                                Commission_Rate__c,
                                Client_Manager__c,
                                StartDate,
                                EndDate,
                                Account.Name,
                                Account.Id
                        FROM 
                                Contract 
                        WHERE 
                                Contract.Id 
                        IN        
                                (SELECT 
                                        Contract_Resource__c.Contract__c
                                FROM
                                        Contract_Resource__c
                                WHERE 
                                        Contract_Resource__c.Id = :contractResourceId)             
                ];

                if(contracts.isEmpty()) {
                        return null;
                }

                return contracts[0];
        }

        public List<Contract> findAll() {
                List<Contract> contracts = [
                        SELECT 
                                Id,
                                ContractNumber,
                                Pricebook2Id,
                                Referred_By__c,
                                Referral_Rate__c,
                                Salesperson__c,
                                Commission_Rate__c,
                                Account.Name,
                                Account.Id
                        FROM 
                                Contract          
                ];

                return contracts;
        }

        public List<Contract> findAllByAccount(String accountId) {
                return (List<Contract>)getWhere(sql_Criteria.Equals(Contract.AccountId, accountId));
        }

        public List<Contract> findAllByStatus(String status) {
                return (List<Contract>)getWhere(sql_Criteria.Equals(Contract.Status, status));
        }

        public List<Contract> findAllBySalesperson(String employeeId) {
                return (List<Contract>)getWhere(sql_Criteria.Equals(Contract.Salesperson__c, employeeId));
        }  

        public List<Contract> findAllByReferral(String accountId) {
                return (List<Contract>)getWhere(sql_Criteria.Equals(Contract.Referred_By__c, accountId));
        }

        public List<Contract> getManagedServicesContractsByAccounts(Set<Id> acctIds) {
                if(acctIds == null || acctIds.isEmpty()) {
                        return new List<Contract>();
                }

                List<String> andCriterias = new List<String> {
                        sql_Criteria.ValueIn(Contract.AccountId, acctIds),
                        sql_Criteria.Equals(Contract.Is_Managed_Services__c, true)
                };

                String criteria = sql_Criteria.AndCriterias(andCriterias);

                return (List<Contract>)getWhere(criteria);
        }      

        public List<Contract> getContractsWithSalesperson() {
                String status = 'Activated';

                String criteria = sql_Criteria.AndCriterias(new List<String> {
                        sql_Criteria.IsNotNull(Contract.Salesperson__c),
                        sql_Criteria.Equals(Contract.Status, status)
                });

                return (List<Contract>)getWhere(criteria);
        }

        public List<Contract> getContractsWithReferral() {
                String status = 'Activated';

                String criteria = sql_Criteria.AndCriterias(new List<String> {
                        sql_Criteria.IsNotNull(Contract.Referred_By__c),
                        sql_Criteria.Equals(Contract.Status, status)
                });

                return (List<Contract>)getWhere(criteria);
        }
}