force-app/main/default/objects/Account/fields/Send_Invoice_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Send Invoice To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Send_Invoice_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Send Invoice To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Send Invoice To)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/Contract_Resource__c.object-meta.xml
<CustomObject>
    <label>Contract Resource</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Contract Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Resource__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Resources</relationshipLabel>
    <relationshipName>Contract_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Resource__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dao_Account.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 */
public with sharing class dao_Account extends sql_Dao {
    public dao_Account() {
        setSObject(Account.sObjectType);

        addField(Account.Id);
        addField(Account.Name);
        addField(Account.Send_Invoice_To__c);
    }

    //SANDBOX 
    public List<Account> findAccountsByNames(Set<String> names) {
        if(names == null || names.isEmpty()) {
            return new List<Account>();
        }
        addOrderBy(sql_Order.Ascending(Account.Name));
        return (List<Account>)getWhere(sql_Criteria.ValueIn(Account.Name, names));
    }

    public Account findOne(String accountId) {
        List<Account> accounts = getWhere(sql_Criteria.Equals(Account.Id, accountId));
        
        if(accounts.isEmpty()) {
            return null;
        }

        return accounts[0];
    }

    public List<Account> findAll() {
        addOrderBy(sql_Order.Ascending(Account.Name));
        return (List<Account>)getAll();
    }

    public List<Account> findAllByIds(Set<String> ids) {
        if(ids == null || ids.isEmpty()) {
            return new List<Account>();
        }
        addOrderBy(sql_Order.Ascending(Account.Name));
        return (List<Account>)getWhere(sql_Criteria.ValueIn(Account.Id, ids));
    }

    public List<Account> findAllByNames(Set<String> names) {
        if(names == null || names.isEmpty()) {
            return new List<Account>();
        }
        addOrderBy(sql_Order.Ascending(Account.Name));
        return (List<Account>)getWhere(sql_Criteria.ValueIn(Account.Name, names));
    }

    public List<Account> findAllWithContracts(String status, String employeeId, String contractResourceId, Set<String> contractIds) {
        sql_Query contractsQuery = new sql_Query();

        contractsQuery.setSObject('Contracts');
        
        contractsQuery.addField(Contract.Id);
        contractsQuery.addField(Contract.ContractNumber);
        contractsQuery.addField(Contract.Status);
        contractsQuery.addField(Contract.StartDate);
        contractsQuery.addField(Contract.EndDate);

        List<String> listCriterias = new List<String>();

        if(String.isNotBlank(status)) {
            listCriterias.add(sql_Criteria.Equals(Contract.Status, status));
        }

        listCriterias.add(sql_Criteria.ValueIn(Contract.Id, createContractResourcesQuery(contractResourceId, employeeId, contractIds)));
        contractsQuery.setCriteria(sql_Criteria.AndCriterias(listCriterias));

        addChild(contractsQuery);
        addOrderBy(sql_Order.Ascending(Account.Name));
        List<Account> listAccounts = getAll();

        query.children.clear();

        return listAccounts;
    }

    private sql_Query createContractResourcesQuery(String contractResourceId, String employeeId, Set<String> contractIds) {
        sql_Query contractsQuery = new sql_Query();

        contractsQuery.setSObject('Contract_Resource__c');
        
        contractsQuery.addField(Contract_Resource__c.Contract__c);

        List<String> listCriterias = new List<String>();

        if(String.isNotBlank(contractResourceId)) {
           listCriterias.add(sql_Criteria.Equals(Contract_Resource__c.Id, contractResourceId));
        } else {
            if(String.isNotBlank(employeeId)) {
                listCriterias.add(sql_Criteria.Equals(Contract_Resource__c.Employee__c, employeeId));
            }

            if(contractIds != null && !contractIds.isEmpty()) {
                listCriterias.add(sql_Criteria.ValueIn(Contract_Resource__c.Contract__c, contractIds));
            }
        }

        if(listCriterias.size() > 0) {
            contractsQuery.setCriteria(sql_Criteria.AndCriterias(listCriterias));
        }

        return contractsQuery;
    }
}