force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/dueDate__c.field-meta.xml
<CustomField>
    <fullName>dueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/is_Paid__c.field-meta.xml
<CustomField>
    <fullName>is_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/issueDate__c.field-meta.xml
<CustomField>
    <fullName>issueDate__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Last_updated__c.field-meta.xml
<CustomField>
    <fullName>Last_updated__c</fullName>
    <label>Last updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/paymentDate__c.field-meta.xml
<CustomField>
    <fullName>paymentDate__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dao_Invoices.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public with sharing class dao_Invoices extends sql_Dao {

    public dao_Invoices() {
      setSObject(Invoice__c.sObjectType);

      addField(Invoice__c.Id);
      addField(Invoice__c.Name);
      addField(Invoice__c.startDate__c);
      addField(Invoice__c.endDate__c);
      addField(Invoice__c.Status__c);
      addField(Invoice__c.Account__c);
      addField(Invoice__c.dueDate__c);
      addField(Invoice__c.issueDate__c);
      addField(Invoice__c.is_Paid__c);
      addField(Invoice__c.Amount__c);
      addField(Invoice__c.paymentDate__c);
      addField(Invoice__c.Expenses__c);
      addField(Invoice__c.Minutes__c);
      addField(Invoice__c.invoice.Last_updated__c);
    }

     public Invoice__c findOne(String invoiceId) {
          List<Invoice__c>  invoices = getWhere(sql_Criteria.Equals(Invoice__c.Id, invoiceId));

          if(invoices.isEmpty()) {
               return null;
          }

          return invoices[0];
     }

     public Invoice__c findOneByDates(Map<String, Object> conditions) {
          if(conditions == null || conditions.isEmpty()) {
               return null;
          }

          Date startDate = (Date)conditions.get('startDate');
          Date endDate = (Date)conditions.get('endDate');
          
          if(startDate == null || endDate == null) {
               return null;
          }

          String startDateCriteria = sql_Criteria.LessThanEquals(Invoice__c.startDate__c, startDate);
          String endDateCriteria = sql_Criteria.GreaterThanEquals(Invoice__c.endDate__c, endDate);

          List<String> andCriteria = new List<String>{
               startDateCriteria,
               endDateCriteria
          };

          String status = (String)conditions.get('status');
          if(status != null) {
               andCriteria.add(sql_Criteria.Equals(Invoice__c.Status__c, status));
          }
          
          String accountId = (String)conditions.get('accountId');
          if(accountId != null) {
               andCriteria.add(sql_Criteria.Equals(Invoice__c.Account__c, accountId));
          }
          
          List<Invoice__c> invoices = getWhere(sql_Criteria.AndCriterias(andCriteria));

          if(invoices.isEmpty()) {
               return null;
          }

          return invoices[0];
     }

     public List<Invoice__c> findAll(Integer limits, Integer offsets) {//TODO: remove parameters
          return (List<Invoice__c>)getAll();
     }

     public List<Invoice__c> findAllByParams(Map<String, Object> conditions) {
          if(conditions == null || conditions.isEmpty()) {
               return new List<Invoice__c>();
          }

          List<String> andCriteria = new List<String>{};

          Date startDate = (Date)conditions.get('startDate');
          if(startDate != null) {
               andCriteria.add(sql_Criteria.GreaterThanEquals(Invoice__c.startDate__c, startDate));
          }

          Date endDate = (Date)conditions.get('endDate');
          if(endDate != null) {
               andCriteria.add(sql_Criteria.LessThanEquals(Invoice__c.endDate__c, endDate));
          }

          Set<String> accountIds = (Set<String>)conditions.get('accountIds');
          if(accountIds != null) {
               andCriteria.add(sql_Criteria.ValueIn(Invoice__c.Account__c, accountIds));
          }
          
         
          String status = (String)conditions.get('status');
          if(status != null) {
               String statusCriteria = sql_Criteria.Equals(Invoice__c.Status__c, status);

               Date pendingInvoicesStartDate = (Date)conditions.get('pendingInvoicesStartDate');
               if(pendingInvoicesStartDate != null && status == 'Pending') {
                    Datetime pendingInvoicesStartDatetime = Datetime.newInstance(pendingInvoicesStartDate.year(), pendingInvoicesStartDate.month(), pendingInvoicesStartDate.day());
                    String pendingInvoicesStartDateCriteria = sql_Criteria.GreaterThanEquals(Invoice__c.Last_updated__c, pendingInvoicesStartDatetime);
                    andCriteria.add(pendingInvoicesStartDateCriteria);
               }
          }

          if(andCriteria.isEmpty()) {
               return new List<Invoice__c>();
          }

          return (List<Invoice__c>)getWhere(sql_Criteria.AndCriterias(andCriteria));
     }

    public Boolean checkDatesInPeriods(Map<String, Object> conditions) {
          if(conditions == null || conditions.isEmpty()) {
               return true;
          }

          String accountId = (String)conditions.get('accountId');
          Date startDate = (Date)conditions.get('startDate');
          Date endDate = (Date)conditions.get('endDate');

          if(accountId == null || startDate == null || endDate == null) {
               return true;
          }

          String invoiceId = (String)conditions.get('invoiceId');

          List<String> andCriteria = new List<String>();
          andCriteria.add(sql_Criteria.Equals(Invoice__c.Account__c, accountId));

          if(String.isNotBlank(invoiceId)) {
               andCriteria.add(sql_Criteria.NotEquals(Invoice__c.Id, invoiceId));
          }  

          List<Invoice__c> invoices = getWhere(sql_Criteria.AndCriterias(andCriteria)); 

          for(Invoice__c invoice : invoices) {
               if(invoice.startDate__c <= startDate && invoice.endDate__c >= startDate){
                    return false;
               }
               if(invoice.startDate__c >= startDate && invoice.endDate__c <= endDate){
                    return false;
               }
               if(invoice.startDate__c <= endDate && invoice.endDate__c >= endDate){
                    return false;
               }
               if(invoice.startDate__c <= startDate && invoice.endDate__c >= endDate){
                    return false;
               }
          }

          return true;
    }
}