force-app/main/default/objects/Monthly_Managed_Service__c/Monthly_Managed_Service__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service</label>
    <nameField>
        <displayFormat>MMS-{000000000}</displayFormat>
        <label>Monthly Managed Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/Monthly_Managed_Service_Activity__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service Activity</label>
    <nameField>
        <displayFormat>MMSA-{000000000}</displayFormat>
        <label>Monthly Managed Service Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Service Activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Monthly_Managed_Service__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Managed_Service__c</fullName>
    <label>Monthly Managed Service</label>
    <referenceTo>Monthly_Managed_Service__c</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controller_ManagedServiceInvoice.cls
public with sharing class controller_ManagedServiceInvoice 
{
    private dao_MonthlyManagedService daoMonthlyManagedService = new dao_MonthlyManagedService();
    private dao_MonthlyManagedServiceActivity daoMonthlyManagedServiceActivity = new dao_MonthlyManagedServiceActivity();

	public Monthly_Managed_Service__c mms { get; set; }
    public List<Monthly_Managed_Service_Activity__c> mmsaList { get; set; }

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public controller_ManagedServiceInvoice(ApexPages.StandardController stdController) 
    {
        this.mms = (Monthly_Managed_Service__c) stdController.getRecord();
        this.mms = (Monthly_Managed_Service__c) daoMonthlyManagedService.getById(mms.Id);

        Set<Id> mmsIds = new Set<Id> { mms.Id };

        this.mmsaList = daoMonthlyManagedServiceActivity.getMonthlyManagedServiceActivitiesByMMS(mmsIds);
    }

    public String getRecordName() 
    {
        return 'Hello World!';
    }
}