force-app/main/default/objects/Monthly_Managed_Service__c/Monthly_Managed_Service__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service</label>
    <nameField>
        <displayFormat>MMS-{000000000}</displayFormat>
        <label>Monthly Managed Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Monthly Managed Services</relationshipLabel>
    <relationshipName>Monthly_Managed_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Case_Allotment__c.field-meta.xml
<CustomField>
    <fullName>Case_Allotment__c</fullName>
    <inlineHelpText>Number of cases available, including what was carried over from last month.</inlineHelpText>
    <label>Case Allotment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Case_Overage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Case_Overage_Cost__c</fullName>
    <inlineHelpText>Charged by the Case.</inlineHelpText>
    <label>Case Overage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Cases_Over__c.field-meta.xml
<CustomField>
    <fullName>Cases_Over__c</fullName>
    <formula>IF(((Total_Cases__c -  Case_Allotment__c) &lt; 0), 0, Total_Cases__c -  Case_Allotment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cases Over</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Cases_to_Carryover__c.field-meta.xml
<CustomField>
    <fullName>Cases_to_Carryover__c</fullName>
    <formula>IF(((Case_Allotment__c -  Total_Cases__c) &lt; 0), 0, Case_Allotment__c -  Total_Cases__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cases to Carryover</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Developer_Hours__c</fullName>
    <inlineHelpText>Number of developer hours available, including what was carried over from last month.</inlineHelpText>
    <label>Developer Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Hours_Over__c.field-meta.xml
<CustomField>
    <fullName>Developer_Hours_Over__c</fullName>
    <formula>IF(((Total_Developer_Hours__c -  Developer_Hours__c) &lt; 0), 0, Total_Developer_Hours__c -  Developer_Hours__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Developer Hours Over</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Hours_to_Carryover__c.field-meta.xml
<CustomField>
    <fullName>Developer_Hours_to_Carryover__c</fullName>
    <formula>IF(((Developer_Hours__c -  Total_Developer_Hours__c) &lt; 0), 0, Developer_Hours__c -  Total_Developer_Hours__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Developer Hours to Carryover</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Developer_Overage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Developer_Overage_Cost__c</fullName>
    <inlineHelpText>Charged for each hour over.</inlineHelpText>
    <label>Developer Overage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Monthly_Base_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Base_Cost__c</fullName>
    <label>Monthly Base_Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Monthly_Case_Overage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Case_Overage_Cost__c</fullName>
    <formula>Cases_Over__c * Case_Overage_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This equals the number of cases over, times the case overage cost.</inlineHelpText>
    <label>Monthly Case Overage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Monthly_Developer_Overage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Developer_Overage_Cost__c</fullName>
    <formula>Developer_Hours_Over__c *  Developer_Overage_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This equals the number developer hours over, times the developer overage cost.</inlineHelpText>
    <label>Monthly Developer Overage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Monthly_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Total_Cost__c</fullName>
    <formula>Monthly_Base_Cost__c + Monthly_Case_Overage_Cost__c + Monthly_Developer_Overage_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is the monthly case cost, plus any overages.</inlineHelpText>
    <label>Monthly Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Total_Cases__c.field-meta.xml
<CustomField>
    <fullName>Total_Cases__c</fullName>
    <label>Total Cases</label>
    <summaryFilterItems>
        <field>Monthly_Managed_Service_Activity__c.Activity_Type__c</field>
        <operation>equals</operation>
        <value>Case</value>
    </summaryFilterItems>
    <summaryForeignKey>Monthly_Managed_Service_Activity__c.Monthly_Managed_Service__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service__c/fields/Total_Developer_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Developer_Hours__c</fullName>
    <label>Total Developer Hours</label>
    <summarizedField>Monthly_Managed_Service_Activity__c.Development_Time_Hours__c</summarizedField>
    <summaryFilterItems>
        <field>Monthly_Managed_Service_Activity__c.Activity_Type__c</field>
        <operation>equals</operation>
        <value>Development</value>
    </summaryFilterItems>
    <summaryForeignKey>Monthly_Managed_Service_Activity__c.Monthly_Managed_Service__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/dao_MonthlyManagedService.cls
public with sharing class dao_MonthlyManagedService extends sql_Dao
{
	public dao_MonthlyManagedService() 
	{
		setSObject(Monthly_Managed_Service__c.sObjectType);

		addField(Monthly_Managed_Service__c.Id);
		addField(Monthly_Managed_Service__c.Name);
		addField(Monthly_Managed_Service__c.Account__c);
		addField(Monthly_Managed_Service__c.Begin_Date__c);
		addField(Monthly_Managed_Service__c.Case_Allotment__c);
		addField(Monthly_Managed_Service__c.Case_Overage_Cost__c);
		addField(Monthly_Managed_Service__c.Cases_Over__c);
		addField(Monthly_Managed_Service__c.Cases_to_Carryover__c);
		addField(Monthly_Managed_Service__c.Developer_Hours__c);
		addField(Monthly_Managed_Service__c.Developer_Hours_Over__c);
		addField(Monthly_Managed_Service__c.Developer_Hours_to_Carryover__c);
		addField(Monthly_Managed_Service__c.Developer_Overage_Cost__c);
		addField(Monthly_Managed_Service__c.End_Date__c);
		addField(Monthly_Managed_Service__c.Monthly_Base_Cost__c);
		addField(Monthly_Managed_Service__c.Monthly_Case_Overage_Cost__c);
		addField(Monthly_Managed_Service__c.Monthly_Developer_Overage_Cost__c);
		addField(Monthly_Managed_Service__c.Monthly_Total_Cost__c);
		addField(Monthly_Managed_Service__c.Total_Cases__c);
		addField(Monthly_Managed_Service__c.Total_Developer_Hours__c);

		addField('Account__r.Name');
		addField('Account__r.BillingStreet');
		addField('Account__r.BillingCity');
		addField('Account__r.BillingState');
		addField('Account__r.BillingPostalCode');
	}

	public List<Monthly_Managed_Service__c> getMonthlyManagedServicesByAccounts(Set<Id> acctIds)
	{
		return (List<Monthly_Managed_Service__c>) getWhere(sql_Criteria.ValueIn(Monthly_Managed_Service__c.Account__c, acctIds));
	}

	public List<Monthly_Managed_Service__c> getMonthlyManagedServicesByAccountsAndDates(Set<Id> acctIds, Date beginDate, Date endDate)
	{
		String criteria = sql_Criteria.AndCriterias(new List<String> {
			sql_Criteria.ValueIn(Monthly_Managed_Service__c.Account__c, acctIds),
			sql_Criteria.Equals(Monthly_Managed_Service__c.Begin_Date__c, beginDate),
			sql_Criteria.Equals(Monthly_Managed_Service__c.End_Date__c, endDate)
		});
		return (List<Monthly_Managed_Service__c>) getWhere(criteria);
	}
}