force-app/main/default/objects/Monthly_Managed_Service__c/Monthly_Managed_Service__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service</label>
    <nameField>
        <displayFormat>MMS-{000000000}</displayFormat>
        <label>Monthly Managed Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/Monthly_Managed_Service_Activity__c.object-meta.xml
<CustomObject>
    <label>Monthly Managed Service Activity</label>
    <nameField>
        <displayFormat>MMSA-{000000000}</displayFormat>
        <label>Monthly Managed Service Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Managed Service Activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <label>Date Opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Development_Time_Hours__c.field-meta.xml
<CustomField>
    <fullName>Development_Time_Hours__c</fullName>
    <label>Development Time (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Monthly_Managed_Service__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Managed_Service__c</fullName>
    <label>Monthly Managed Service</label>
    <referenceTo>Monthly_Managed_Service__c</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Who_Closed__c.field-meta.xml
<CustomField>
    <fullName>Who_Closed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who Closed</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Managed_Service_Activity__c/fields/Who_Opened__c.field-meta.xml
<CustomField>
    <fullName>Who_Opened__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who Opened</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monthly Managed Service Activity</relationshipLabel>
    <relationshipName>Monthly_Managed_Service_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dao_MonthlyManagedServiceActivity.cls
public with sharing class dao_MonthlyManagedServiceActivity extends sql_Dao
{
	public dao_MonthlyManagedServiceActivity() 
	{
		setSObject(Monthly_Managed_Service_Activity__c.sObjectType);

		addField(Monthly_Managed_Service_Activity__c.Id);
		addField(Monthly_Managed_Service_Activity__c.Name);
		addField(Monthly_Managed_Service_Activity__c.Activity_Type__c);
		addField(Monthly_Managed_Service_Activity__c.Case__c);
		addField(Monthly_Managed_Service_Activity__c.Date_Closed__c);
		addField(Monthly_Managed_Service_Activity__c.Date_Opened__c);
		addField(Monthly_Managed_Service_Activity__c.Development_Time_Hours__c);
		addField(Monthly_Managed_Service_Activity__c.Monthly_Managed_Service__c);
		addField(Monthly_Managed_Service_Activity__c.Summary__c);
		addField(Monthly_Managed_Service_Activity__c.Who_Closed__c);
		addField(Monthly_Managed_Service_Activity__c.Who_Opened__c);

		addField('Case__r.CaseNumber');
		addField('Who_Closed__r.Name');
		addField('Who_Closed__r.Title');
		addField('Who_Opened__r.Name');
		addField('Who_Opened__r.Title');
	}

	public List<Monthly_Managed_Service_Activity__c> getMonthlyManagedServiceActivitiesByCases(Set<Id> caseIds)
	{
		return (List<Monthly_Managed_Service_Activity__c>) getWhere(sql_Criteria.ValueIn(Monthly_Managed_Service_Activity__c.Case__c, caseIds));
	}

	public List<Monthly_Managed_Service_Activity__c> getMonthlyManagedServiceActivitiesByMMS(Set<Id> mmsIds)
	{
		return (List<Monthly_Managed_Service_Activity__c>) getWhere(sql_Criteria.ValueIn(Monthly_Managed_Service_Activity__c.Monthly_Managed_Service__c, mmsIds));
	}
}