force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/is_Paid__c.field-meta.xml
<CustomField>
    <fullName>is_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Is_Paid_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Is_Paid_Invoices__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid Invoices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Is_Pending_invoices__c.field-meta.xml
<CustomField>
    <fullName>Is_Pending_invoices__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending invoices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Last_updated__c.field-meta.xml
<CustomField>
    <fullName>Last_updated__c</fullName>
    <label>Last updated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_type__c.field-meta.xml
<CustomField>
    <fullName>Payment_type__c</fullName>
    <label>Payment type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subcontractor</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Commissions</fullName>
            </value>
            <value>
                <fullName>Expenses Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/paymentDate__c.field-meta.xml
<CustomField>
    <fullName>paymentDate__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Pending_invoices_startDate__c.field-meta.xml
<CustomField>
    <fullName>Pending_invoices_startDate__c</fullName>
    <label>Pending invoices start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/ReceiverId__c.field-meta.xml
<CustomField>
    <fullName>ReceiverId__c</fullName>
    <label>Receiver Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Total_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes__c</fullName>
    <label>Total Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/dao_Payments.cls
/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 */
public with sharing class dao_Payments extends sql_Dao {
    public dao_Payments() {
        setSObject(Payment__c.sObjectType);

        addField(Payment__c.Id);
        addField(Payment__c.Name);
        addField(Payment__c.ReceiverId__c);
        addField(Payment__c.startDate__c);
        addField(Payment__c.endDate__c);
        addField(Payment__c.Last_updated__c);
        addField(Payment__c.Is_Paid_Invoices__c);
        addField(Payment__c.Payment_type__c);
        addField(Payment__c.Is_Pending_invoices__c);
        addField(Payment__c.Pending_invoices_startDate__c);
        addField(Payment__c.Status__c);
        addField(Payment__c.Total_Amount__c);
        addField(Payment__c.Total_Minutes__c);
        addField(Payment__c.is_Paid__c);
        addField(Payment__c.paymentDate__c);
    }

    public Payment__c findOne(String paymentId) {
        List<Payment__c> payments = getWhere(sql_Criteria.Equals(Payment__c.Id, paymentId));
        
        if(payments.isEmpty()) {
            return null;
        }

        return payments[0];
    }

    public List<Payment__c> findByIds(Set<String> paymentsIds) {
        if(paymentsIds == null || paymentsIds.isEmpty()) {
            return new List<Payment__c>();
        }

        return (List<Payment__c>)getWhere(sql_Criteria.ValueIn(Payment__c.Id, paymentsIds));
    }

    public List<Payment__c> findAll() {
        addOrderBy(sql_Order.Descending(Payment__c.Name));
        return (List<Payment__c>)getAll();
    }

    public List<Payment__c> findByParams(Map<String, Object> conditions) {
        String criteria = '';

        if(conditions != null && !conditions.isEmpty()) {
            String paymentId = (String)conditions.get('paymentId');
            String paymentType = (String)conditions.get('paymentType');
            String receiverId = (String)conditions.get('receiverId');
            Date startDate = (Date)conditions.get('startDate');
            Date endDate = (Date)conditions.get('endDate');        
            Boolean paidInvoices = (Boolean)conditions.get('paidInvoices');
            Boolean pendingInvoices = (Boolean)conditions.get('pendingInvoices');
            Date pendingInvoicesStartDate = (Date)conditions.get('pendingInvoicesStartDate');

            List<String> andCriteria = new List<String>();

            if(String.isNotBlank(paymentId)) {
                andCriteria.add(sql_Criteria.NotEquals(Payment__c.Id, paymentId));
            }

            if(String.isNotBlank(paymentType)) {
                andCriteria.add(sql_Criteria.Equals(Payment__c.Payment_type__c, paymentType));
            }

            if(String.isNotBlank(receiverId)) {
                andCriteria.add(sql_Criteria.Equals(Payment__c.ReceiverId__c, receiverId));
            }

            Boolean excludeDateRange = (Boolean)conditions.get('excludeDateRange');
            if(excludeDateRange == null || excludeDateRange == false) {
                if(startDate != null) {
                    andCriteria.add(sql_Criteria.GreaterThanEquals(Payment__c.startDate__c, startDate));
                }

                if(endDate != null) {
                    andCriteria.add(sql_Criteria.LessThanEquals(Payment__c.endDate__c, endDate));
                }
            }

            if(paidInvoices != null) {
                andCriteria.add(sql_Criteria.Equals(Payment__c.Is_Paid_Invoices__c, paidInvoices));
            }

            if(pendingInvoices != null && pendingInvoicesStartDate != null) {
                andCriteria.add(sql_Criteria.Equals(Payment__c.Is_Pending_invoices__c, pendingInvoices));
                andCriteria.add(sql_Criteria.GreaterThanEquals(Payment__c.Pending_invoices_startDate__c, pendingInvoicesStartDate));
            }

            if(!andCriteria.isEmpty()) {
                criteria = sql_Criteria.AndCriterias(andCriteria);
            }
        }

        return (List<Payment__c>)getWhere(criteria);
    }

    public Boolean existPaymentsInPeriod(Map<String, Object> conditions) {
        if(conditions == null || conditions.isEmpty()) {
            return false;
        }

        conditions.put('excludeDateRange', true);        
        List<Payment__c> payments = findByParams(conditions);

        Date startDate = (Date)conditions.get('startDate');
        Date endDate = (Date)conditions.get('endDate');

        for(Payment__c payment : payments) {
             if(payment.startDate__c <= startDate && payment.endDate__c >= startDate){
                  return true;
             }
             if(payment.startDate__c >= startDate && payment.endDate__c <= endDate){
                  return true;
             }
             if(payment.startDate__c <= endDate && payment.endDate__c >= endDate){
                  return true;
             }
             if(payment.startDate__c <= startDate && payment.endDate__c >= endDate){
                  return true;
             }
        }

        return false;
    }
}