force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <displayFormat>PAYLI-{000}</displayFormat>
        <label>Payment Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DIPaymentsScratchOrgDataFactory.cls
public without sharing class DIPaymentsScratchOrgDataFactory {
  public static List<Payment_Line_Item__c> getPaymentsLineItemsFromDb() {
    return [SELECT id FROM Payment_Line_Item__c];
  }

  public static List<Payment__c> getPaymentsFromDb() {
    return [SELECT id FROM Payment__c];
  }

  public static void deleteTestData() {
    List<Payment_Line_Item__c> paymentLineItems = getPaymentsLineItemsFromDb();
    delete paymentLineItems;

    List<Payment__c> payments = getPaymentsFromDb();
    delete payments;
  }
}