force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Line Item</label>
    <nameField>
        <displayFormat>PAYLI-{000}</displayFormat>
        <label>Payment Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Line_Item__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Line Items</relationshipLabel>
    <relationshipName>Payment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/dao_PaymentsLineItemTest.cls
@isTest
public with sharing class dao_PaymentsLineItemTest {
    @testSetup static void setup() {
        DIPaymentsTestDataFactory.init();
    }

    @isTest static void FindByPayment_PaymentIdExistInDB_ReturnNotEmptyList() {
        Boolean expectNotEmptyList = true;
        Integer sizeEmptyList = 0;
         
        Payment__c payment = DIPaymentsTestDataFactory.getPayment(DIPaymentsTestDataFactory.PAYMENT_STATUS_NEW);
        String paymentId = payment.Id;

        Test.startTest();

        dao_PaymentsLineItem daoPaymentsLineItem = new dao_PaymentsLineItem();
        List<Payment_Line_Item__c> resultListItems = daoPaymentsLineItem.findByPayment(paymentId);
        System.debug('@@@ FindByPayment_PaymentIdExistInDB_ReturnNotEmptyList:result: ' + resultListItems);

        System.assertEquals(expectNotEmptyList, resultListItems.size() > sizeEmptyList);

        Test.stopTest();
    }

    @isTest static void FindByPayment_PaymentIdNotExistInDB_ReturnEmptyList() {
        Integer expectSizeEmptyList = 0;
         
        String paymentId = TestDataFactory.getNotExistId();

        Test.startTest();

        dao_PaymentsLineItem daoPaymentsLineItem = new dao_PaymentsLineItem();
        List<Payment_Line_Item__c> resultListItems = daoPaymentsLineItem.findByPayment(paymentId);
        System.debug('@@@ FindByPayment_PaymentIdNotExistInDB_ReturnEmptyList:result: ' + resultListItems);

        System.assertEquals(expectSizeEmptyList, resultListItems.size());

        Test.stopTest();
    }

    @isTest static void FindByPayment_PaymentIdNull_ReturnEmptyList() {
        Integer expectSizeEmptyList = 0;
         
        String paymentId = null;

        Test.startTest();

        dao_PaymentsLineItem daoPaymentsLineItem = new dao_PaymentsLineItem();
        List<Payment_Line_Item__c> resultListItems = daoPaymentsLineItem.findByPayment(paymentId);
        System.debug('@@@ FindByPayment_PaymentIdNull_ReturnEmptyList:result: ' + resultListItems);

        System.assertEquals(expectSizeEmptyList, resultListItems.size());

        Test.stopTest();
    }
}